const customers = [
	{
		customerName: "Jane Cooper",
		company: "Microsoft",
		phoneNumber: "(225) 555-0118",
		email: "jane@microsoft.com",
		country: "United States",
		staus: "Active",
	},
	{
		customerName: "Floyd Miles",
		company: "Yahoo",
		phoneNumber: "(205) 555-0100",
		email: "floyd@yahoo.com",
		country: "Kiribati",
		staus: "Active",
	},
	{
		customerName: "Ronald Richards",
		company: "Adobe",
		phoneNumber: "(302) 555-0107",
		email: "ronald@adobe.com",
		country: "Israel",
		staus: "Active",
	},
	{
		customerName: "Marvin McKinney",
		company: "Tesla",
		phoneNumber: "(252) 555-0126",
		email: "marvin@tesla.com",
		country: "Iran",
		staus: "Active",
	},
	{
		customerName: "Jerome Bell",
		company: "Google",
		phoneNumber: "(629) 555-0129",
		email: "jerome@google.com",
		country: "Réunion",
		staus: "Active",
	},
	{
		customerName: "Kathryn Murphy",
		company: "Microsoft",
		phoneNumber: "(406) 555-0120",
		email: "kathryn@microsoft.com",
		country: "Curaçao",
		staus: "Active",
	},
	{
		customerName: "Jacob Jones",
		company: "Yahoo",
		phoneNumber: "(208) 555-0112",
		email: "jacob@yahoo.com",
		country: "Brazil",
		staus: "Active",
	},
	{
		customerName: "Kristin Watson",
		company: "Facebook",
		phoneNumber: "(704) 555-0127",
		email: "kristin@facebook.com",
		country: "Åland Islands",
		staus: "Active",
	},
	{
		customerName: "Jane",
		company: "Microsoft",
		phoneNumber: "(225) 555-0118",
		email: "jane@microsoft.com",
		country: "United States",
		staus: "Active",
	},
	{
		customerName: "Floyd",
		company: "Yahoo",
		phoneNumber: "(205) 555-0100",
		email: "floyd@yahoo.com",
		country: "Kiribati",
		staus: "Active",
	},
	{
		customerName: "Ronald",
		company: "Adobe",
		phoneNumber: "(302) 555-0107",
		email: "ronald@adobe.com",
		country: "Israel",
		staus: "Active",
	},
	{
		customerName: "Marvin",
		company: "Tesla",
		phoneNumber: "(252) 555-0126",
		email: "marvin@tesla.com",
		country: "Iran",
		staus: "Active",
	},
	{
		customerName: "Jerome",
		company: "Google",
		phoneNumber: "(629) 555-0129",
		email: "jerome@google.com",
		country: "Réunion",
		staus: "Active",
	},
	{
		customerName: "Kathryn",
		company: "Microsoft",
		phoneNumber: "(406) 555-0120",
		email: "kathryn@microsoft.com",
		country: "Curaçao",
		staus: "Active",
	},
	{
		customerName: "Jacob",
		company: "Yahoo",
		phoneNumber: "(208) 555-0112",
		email: "jacob@yahoo.com",
		country: "Brazil",
		staus: "Active",
	},
	{
		customerName: "Kristin",
		company: "Facebook",
		phoneNumber: "(704) 555-0127",
		email: "kristin@facebook.com",
		country: "Åland Islands",
		staus: "Active",
	}
];

export default customers;
